### ISSUE TITLE
Validity Check failed

### ISSUE THREAD

**Issue by priosshrsth** [KaOS-Community-Packages/vstudio#1]
Validating source files with md5sums...
    vstudio_x64_lin-deb ... FAILED
ERROR: One or more files did not pass the validity check!
on latest kaos linux 2017.09

**Comment by fjmorazan** [comment]
Hi @priosshrsth,
You can [apply for membership](https://kaosx.us/docs/kcp/) and get access to all PKGBUILDs in KCP so that you can update any PKGBUILD
In the case of this package it hasn't been updated the PKGBUILD since **a year ago**, so I'll update it just **this** time 😁
